title: CYBWithFlourish's Portfolio
description: >-
   Cyber Security | Purple ğŸŸ£ teaming | Aspiring Ethical Hacker, 
  Pen tester, ğŸ bounter | Vibe Coder | Kali, Python, AI, | Web3
  
author:
  name: CYBWithFlourish
  github_username: CYBWithFlourish
  email: nill
  
social:
  links:
    - https://linkedin.com/in/cybflourish/
    - https://github.com/CYBWithFlourish
    - https://instagram.com/cybwithflourish/
    - https://medium.com/@cybwithflourish/
    - https://dev.to/cybwithflourish/

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-feed


